logging:
  level:
    root: WARN
spring:
  jpa:
    show-sql: true
    use-sql-comments: true
    format-sql: true
    defer-datasource-initialization=true:
  datasource:
    generate-unique-name: false
    name: giftApp